###########
#  site.title, site.url, site.path

title: 'Planet Jekyll'

## note: in path do NOT include root (trailing slash) e.g. (/) - use empty string instead
path:  ''
url:   'http://planetjekyll.github.io'


########
# more settings

markdown: kramdown


collections:
  snippets:
    output: true


sass:
  sass_dir: css
  style:    expanded


include:
- _data

exclude:
- README.md
- _snippets/README.md
- attic


safe: true
lsi: false

