###########
#  site.title, site.url, site.path

title: 'Planet Jekyll'

## note: in path do NOT include root (trailing slash) e.g. (/) - use empty string instead
path:    ''
baseurl: ''
url:   'http://planetjekyll.github.io'


########
# more settings

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false


collections:
  snippets:
    output: true


permalink:  /news/:title.html

sass:
  sass_dir: css
  style:    expanded


include:
- _data

exclude:
- README.md
- _snippets/README.md
- _data/showcase/README.md
- attic


safe: true
lsi: false
