###########
# site.url, site.title

url:   'http://planetjekyll.github.io'
title: 'Planet Jekyll'

########
# more settings

markdown: kramdown

collections:
  links:
    output: true

sass:
  sass_dir: css
  style:    expanded


exclude:
- README.md
- QUICKREF.md


safe: true
lsi: false

