###########
# site.url, site.title

url:   'http://planetjekyll.github.io'
title: 'Planet Jekyll'

########
# more settings

markdown: kramdown


collections:
  snippets:
    output: true


sass:
  sass_dir: css
  style:    expanded


include:
- _data

exclude:
- README.md
- _data/links/README.md
- _data/links/attic
- attic


safe: true
lsi: false

